### ISSUE TITLE
IsConnected returning false when on 3G Network (4G untested) iOS 10.0

### ISSUE THREAD

**Issue by UKDeveloper99** [jamesmontemagno/ConnectivityPlugin#26]
I have a live app on the App Store that has recently been updated with the latest version of Xamarin and Xcode 8 iOS 10.0 etc. It uses the latest version of your ConnectivityPlugin. If I'm on a 3G Network on an iOS 9 device the connectivity plugin works as expected.

However on an iPhone 6 test device we have, if it is connected to 3G network it returns false for isConnected.

**Comment by jamesmontemagno** [comment]
Can you try the latest beta and see how that works? I am testing here and it seems alright.

**Comment by JasonBro** [comment]
Hi James,

I'm getting a similar problem on my iOS 10 iPhone. I think it's a race condition due to the Task.Run in this bit of code  :-

ConnectivityPlugin/src/Connectivity.Plugin.iOSUnified/ConnectivityImplementation.cs

public ConnectivityImplementation()
{
    //start an update on the background.
    **Task.Run(() => { UpdateConnected(false);});**
    Reachability.ReachabilityChanged += ReachabilityChanged;
}

This is my test code:-

bool connected = CrossConnectivity.Current.IsConnected;  **// returns false**
await Task.Delay(1000);
bool newConnected = CrossConnectivity.Current.IsConnected;   **// returns true**

I'm using the latest beta V2.3.0-beta4, and my device is connected using WiFi.

I hope this helps and sorry about being lazy and not fixing it!

Cheers

Jason

**Comment by jamesmontemagno** [comment]
Where are you testing the IsConnected? Is it at startup somewhere?

The reason for launching in background was to ensure things didn't lock the UI thread..

**Comment by JasonBro** [comment]
No, it's not called at startup - I call it when I navigate to my Feedback
page. The first call I make with the ConnectivityPlugin is this call to
IsConnected and my guess is that ConnectivityPlugin is implemented as a
singleton and the singleton object isn't created until it's first used.

**Comment by jamesmontemagno** [comment]
Interesting... let me investigate a it here.

**Comment by jamesmontemagno** [comment]
Can you try the new beta and let me know if it is still an issue for you.

**Comment by parthnayak7448** [comment]
Hi James, I was also having same issue. I will test new beta version and will let you know. Thanks

**Comment by JasonBro** [comment]
Hi James,

My test works and the code looks like it should work as well, so as far as I am concerned, this should be closed.

Thanks very much for your fast response.

Cheers

Jason

**Comment by jamesmontemagno** [comment]
Lovely :) the new release should be out soon, but I don't think it effects stable to be honest.

**Comment by parthnayak7448** [comment]
Hi James, 

Its Working fine thanks.
