### ISSUE TITLE
[Feature Request] Add .NET Standard Support

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/ConnectivityPlugin#29]

**Comment by LonghronShen** [comment]
Hi, I have forked your repo and try to add an experimental support for .NET Standard 1.6 and .NET Framework 4.5.1.
`https://github.com/LonghronShen/ConnectivityPlugin`
Since a bug in NuGet, the cake build script is now broken.
We can play with the port and see if it is OK.
[Xam.Plugin.Connectivity.2.2.13.zip](https://github.com/jamesmontemagno/ConnectivityPlugin/files/572126/Xam.Plugin.Connectivity.2.2.13.zip)
