### ISSUE TITLE
CrossConnectivity.Current.IsReachable always returns False on Android device

### ISSUE THREAD

**Issue by Nikygm** [jamesmontemagno/ConnectivityPlugin#32]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

statement = await CrossConnectivity.Current.IsReachable("http://www.google.com",5000);
always returns false on android side, iOS wise it's working perfectly. I tried with just google.com and www.google.com and any URL format that was coming into my head, nothing helped.

Version Number of Plugin: 2.2.12
Device Tested On: Samsung GT-P5210
Simulator Tested On:
### Expected Behavior

Returns true because my device can access google.com
### Actual Behavior

Returns false
### Steps to reproduce the Behavior

Use it in PCL and try it on android device
## Feature Request:

Please fill in what you would like
To be working I guess !

**Comment by jamesmontemagno** [comment]
You need to use IsRemoteReachable:

```
 var status = await CrossConnectivity.Current.IsRemoteReachable("google.com");

```

IsReachable is for host names/ip addresses.

**Comment by EmilAlipiev** [comment]
Hi @jamesmontemagno 

Does it only work to query main domain or can we query specific action. For example, I want to check a slow get action of my webservice   because if it times out, i want show user that his connection is slow.    
Something like below. because usually pinging and api is faster than a function in api. Thanks for your help.

`                if (await current.IsRemoteReachable("https://mywebservice.azurewebsites.net/api/getItems/en")==false)`

**Comment by ecaps24** [comment]
Not sure if the last question was answered. I have the same question. Thank you

**Comment by ecaps24** [comment]
So, the version 4.0 isn't available in Nuget ATM?

**Comment by jamesmontemagno** [comment]
4.0 is a pre-release

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Xam.Plugin.Connectivity/4.0.0-beta139
