### ISSUE TITLE
IsConnected returns true even with mobile data and wifi turned off

### ISSUE THREAD

**Issue by devneutz** [jamesmontemagno/ConnectivityPlugin#56]
## Bug 
Xamarin.Forms with Android.
I turned WiFi and mobile data off. CrossConnectivity.Current.IsConnected still returns true. Airplane mode works -> IsConnected returns false.

Version Number of Plugin: 2.3.0
Device Tested On: Samsung Galaxy S7 Edge (Android 6.0.1)

### Expected Behavior
CrossConnectivity.Current.IsConnected returns false.

### Actual Behavior
CrossConnectivity.Current.IsConnected returns true.

**Comment by devneutz** [comment]
My fault, one of the networks is returning connected state. I don't know why yet, I turned everything off.

![grafik](https://cloud.githubusercontent.com/assets/5978985/23168571/ef0972c0-f848-11e6-8dbb-30ed83acee31.png)

**Comment by CurtisHerrick** [comment]
I saw the same behavior and did some debugging with my Samsung S8.  I found that if I check 

`NetworkInfo oAN = manager.ActiveNetworkInfo;
bool isConnected = oAN?.IsConnectedOrConnecting ?? false;`

that it seems to accurately detect whether there is an enabled data network.

With WIFI ON / Mobile Data ON : oAN.Type is Wifi and isConnected is true.
With WIFI ON / Mobile Data OFF : oAN.Type is Wifi and isConnected is true.
With WIFI OFF / Mobile Data ON : oAN.Type is Mobile and isConnected is true.
With WIFI OFF / Mobile Data OFF : oAN is null and therefore isConnected is false.
With  Airplane mode ON : oAN is null and therefore isConnected is false.

Considering now how to best integrate this into the plugin locally.

Should this issue be reopened?  Seems like this would be a good update for the Android side of this plugin.

**Comment by jamesmontemagno** [comment]
Yeah, so this is because it has a Dummy state in it.  I tried to block this out, but caused issues for other users of the code :( unfortunatelly there is not great way to limit them out.

@CurtisHerrick as you can see that would also return true in that state. 

Every android device is different. You should check IsConnected, not IsConnectedOrConnecting as that means it may not actually be connected to a network yet.

**Comment by CurtisHerrick** [comment]
Thanks for the timely response.  Very cool to hear back from the man!  I have posted this info as a new issue / fix / improvement.   I see what you mean about the dummy value, but making this call to get ActiveNetworkInfo seems to have better OS functionality than iterating the available networks.  Sharing the finding incase it's a good find and makes the adapter work more accurately.
:)

**Comment by CurtisHerrick** [comment]
Yeah,  I should definitely just be checking IsConnected.  I'll change that
in my opened issue asap.

Thanks!
- Curtis
via phone gmail

**Comment by jamesmontemagno** [comment]
ActiveNetwork Info will work unless there is multi-sim card and then it doesn't work at all actually. That is why we iterate through it and look for any networks that are active.

**Comment by CurtisHerrick** [comment]
I see your point on the multi-sim scenario.  Hmmm...  Don't get me wrong - not being a bugger - just a bit stuck on this one.  As I run the code now, it iterates through each network and on my Verizon device, two networks show isConnected = True even when Mobile data is disabled.  The adapter then tells my app there's a data connection because it sees networks where IsConnected is true, but there really isn't a data connection.

from https://www.verizonwireless.com/support/knowledge-base-46578/ 
## Edit Access Point Names (APN) - VZAccess Manager (Windows)
LTE Access Point Name (APN) definitions

**vzwims**
Used for connections to IMS services. Required for TXT messaging.

**vzwinternet**
Required for general Internet connections.

**vzwapp**
Required for PDA data service

## What I'm seeing at runtime

Here is what the networks my device sees (both VZWAPP and VZWINS) while Mobile Data is disabled:
ExtraInfo : "VZWAPP" (or) "VZWINS"
IsAvailable : true
IsConnected : true
IsConnectedOrConnecting : true (of course from above)
IsFailover : false
IsRoaming : false
Reason : (null)
SubType : Android.Net.ConnectivityType.Dummy | Android.Net.ConnectivityType.MobileDun | Android.Net.ConnectivityType.Wifi 
SubTypeName : "LTE"
Type : Android.Net.ConnectivityType.Mobile
TypeName : "MOBILE"

The network I also see when "Mobile Data" is enabled is:

ExtraInfo : "VZWINTERNET"
IsAvailable : true
IsConnected : true
IsConnectedOrConnecting : true (of course from above)
IsFailover : false
IsRoaming : false
Reason : "connected"
SubType : Android.Net.ConnectivityType.Dummy | Android.Net.ConnectivityType.MobileDun | Android.Net.ConnectivityType.Wifi 
SubTypeName : "LTE"
Type : Android.Net.ConnectivityType.Mobile
TypeName : "MOBILE"

So.... They look very much the same.  When Mobile Data is enabled, I see all 3 and all 3 have IsConnected == true. When mobile data is disabled, I only see VZWINS and VZWAPP, but both have IsConnected == true.  The only difference I'm seeing (just noticed it actually) is that Reason == "connected" on VZWINTERNET, which is the data connection.  Does it make sense to look for  Reason == "connected" on all of the network info's iterated?  Not a great idea, but it's the best thing I see at this moment... IsConnected isn't accurately telling me that there's a data connection.

Thanks again for your assistance and attention on this!
Curtis Herrick

**Comment by jamesmontemagno** [comment]
First of Curtis thanks for the great response! Love it!

The ActiveNetwork always seems to return the accurate information for you?

**Comment by CurtisHerrick** [comment]
Your multi-Sim scenario sounds like good reason to stick with iterating the networks.  That said, I think I may have found what I (possibly we) may be missing:

## Network Capabilities
https://developer.android.com/reference/android/net/NetworkCapabilities.html

## Examples
https://www.programcreek.com/java-api-examples/index.php?api=android.net.NetworkCapabilities

## Applied to this Plugin
Since NetworkCapabilities was added in API level 21, one could do this correct?

    if ((int)Android.OS.Build.VERSION.SdkInt >= 21)
    {
        foreach (var network in manager.GetAllNetworks())
        {
            NetworkCapabilities oNWC = manager.GetNetworkCapabilities(network);
            if (oNWC?.HasCapability(NetCapability.Internet) ?? false)
            {
                var info = manager.GetNetworkInfo(network);
                if (info?.IsConnected ?? false)
                {
                    return true;
                }
            }                            
        }
    }
    else
    {
        foreach (var info in manager.GetAllNetworkInfo())
        {
            if (info?.IsConnected ?? false)
                return true;
        }
    }

    return false;

I tried it out and it seems to clear up the "IsConnected" confusion my app was having.  What do you think?

**Comment by jamesmontemagno** [comment]
Interesting.... https://developer.android.com/reference/android/net/NetworkCapabilities.html yeah, there are a lot of them.

I mean i think it is correct... I guess if you are on a local wifi with no internet are you still connected?

**Comment by jamesmontemagno** [comment]
Interesting read: https://stackoverflow.com/questions/36358531/internet-check-over-android-net-networkcapabilities-not-working

**Comment by CurtisHerrick** [comment]
It seems to make sense to me to do the following:

- For API < 21 use the code as you've written it.  + Ping if one desires.

- For API >= 21 add the check for Network Capabilities.  + Ping if one desires.

- For API >= 23 also make use of the NET_CAPABILITY_VALIDATED capability check.

As for knowing if the WIFI access point actually has access to the internet, if NET_CAPABILITY_VALIDATED provides that on the cheap, good.  Beyond that, a device can only go so far as to validation of the network it is connecting to beyond what that network is "expected" to do per its capabilities.

If the device is connected to WIFI, but the wifi router has it's network cable pulled, I wouldn't blame the app for claiming that there is a data connection and trying to use it.  Every other thing connected to the router (PC's/etc) would be in the same boat.

What are your thoughts?

**Comment by jamesmontemagno** [comment]
Final one looks like:

```
//When on API 21+ need to use getAllNetworks, else fall base to GetAllNetworkInfo
                //https://developer.android.com/reference/android/net/ConnectivityManager.html#getAllNetworks()
                if ((int)Android.OS.Build.VERSION.SdkInt >= 21)
                {
                    foreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
							var capabilities = manager.GetNetworkCapabilities(network);

							if (capabilities == null)
								continue;

							//check to see if it has the internet capability
							if (!capabilities.HasCapability(NetCapability.Internet))
								continue;

							//if on 23+ then we can also check validated
							//Indicates that connectivity on this network was successfully validated.
							//this means that you can be connected to wifi and has internet
							if ((int)Android.OS.Build.VERSION.SdkInt >= 23 && !capabilities.HasCapability(NetCapability.Validated))
								continue;

							var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable)
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
                }
                else
                {
#pragma warning disable CS0618 // Type or member is obsolete
					foreach (var info in manager.GetAllNetworkInfo())
#pragma warning restore CS0618 // Type or member is obsolete
					{
                        if (info == null || !info.IsAvailable)
                            continue;
                        
                        if (info.IsConnected)
                            return true;
                    }
                }

                return false;
```

**Comment by jamesmontemagno** [comment]
Should be good now, can you test the new beta I push out in a bit, the 3.0 beta is in there and also the 4.0 beta.

**Comment by CurtisHerrick** [comment]
I have tested the code above and it seems to work quite well!  😀

This fix may put to rest a few rumblings of "it always says connected" etc
that I came across when initially searching around for a plugin.  Could
have been in the Xamarin developers forums, etc.  Anyhow - glad to have any
part in the improvement!

I will be out of the office for the next few days, but will aim to test the
beta as noted above.  I'm a bit new to using Nuget in VS, so I may have to
poke around a bit as for how to get the beta version vs the one I'm using.
As for your newer versions, do you know if your dependencies have been
updated any?  I ask because I'm curious if upgrading this plugin might
cause issues with my other Nuget packages that I have in use.  I've seen
cascading update incompatibilities before when upgrading what seemed like
harmless items to upgrade.

Thanks Again!
Curtis Herrick

On Wed, Sep 13, 2017 at 11:54 AM, James Montemagno <notifications@github.com
