### ISSUE TITLE
Windows phone ConnectivityChanged event should fire on every connectivity change and ConnectivityTypeChangedEventArgs.IsConnected should be correct.

### ISSUE THREAD

**Issue by TerryDeCh** [jamesmontemagno/ConnectivityPlugin#62]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3
Device Tested On: Windows phone Nokia Lumina 830.  
Simulator Tested On: Windows Emulator

### Expected Behavior
CrossConnectivity.Current.IsConnected should result In false when not connected.
### Actual Behavior
CrossConnectivity.Current.IsConnected always returns true
### Steps to reproduce the Behavior

run any code against Windows phone device or windows phone emulator

 public App()
        {
            InitializeComponent();
            if(CrossConnectivity.Current.IsConnected)
            {
disconnect internet.

This will always return true.
## Feature Request:
Please fill in what you would like
If there is no internet connection, return false.

**Comment by Koseng** [comment]
IsConnected always returns true (UWP) if there is an activated network interface on windows, no matter if there really is an internet connection. For example on a laptop connected to the internet by WIFI disable WIFI -> IsConnected still returns true but there is no connection. It returns true, due to existing LAN interface (without attached cable).

As stated in the post before this is **wrong**:
`isConnected = profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.None;`

**NetworkConnectivityLevel.LocalAccess is missing**, it also has no internet access.
https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkconnectivitylevel

Change to something like that:
```
isConnected = (profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.None) &&
(profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.LocalAccess);
```
