### ISSUE TITLE
Multiple Cellular types in ConnectionTypes

### ISSUE THREAD

**Issue by c-lamont** [jamesmontemagno/ConnectivityPlugin#66]
## Bug 
In ConnectionTypes I have multiple types of Cellular. See below screen shot.
I have tested this on three different devices and it seems to be specific to Samsung, even when our Samsung A5 had no sim card. Testing on our Sony device did not have this issue.

Version Number of Plugin: 2.3.0
Device Tested On: Samsung S6 and Samsung A5

### Expected Behavior
When switching off Cellular connection, ConnectionTypes should not contain any type of Cellular.

### Actual Behavior
ConnectionTypes always contains at least one type of Cellular. 
When my Cellular connection is on, there are >= 2 types of Cellular in the ConnectionTypes. 
When my Cellular connection is off, there is >= 1 type of Cellular in the ConnectionTypes.

### Steps to reproduce the Behavior
 - Subscribe to the ConnectivityTypeChanged with your Cellular connection off.
 - Switch your Cellular connection on. In your event handler ConnectionTypes will contain >= 2 types of Cellular.
 - Switch your Cellular connection off. In your event handler ConnectionTypes will contain >= 1 type of Cellular.

<img width="881" alt="screen shot 2017-05-19 at 13 26 09" src="https://cloud.githubusercontent.com/assets/24552827/26246217/38b5bb3e-3c98-11e7-9a3f-d845afabb5a7.png">

**Comment by jamesmontemagno** [comment]
It just loops through and checks to see what is actually being reported by the device: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L213

So in this case it seems as though the samsung devices are reporting multiple devices. I mean technically you could with dual sim cards so I do not plan on changing it to only add 1.

It grabs all of the networks and the info:
https://developer.android.com/reference/android/net/NetworkInfo.html

My recommendation here is to run through the valid code that is in the project and let me know exactly what is being returned for the values and if there is some way to detect if it can be skipped in the list.


Since I don't have the exact device and don't fix device specific issues myself I will need some help debugging :)

**Comment by jamesmontemagno** [comment]
I have cleaned this up in the most recent beta 3.0.2
