### ISSUE TITLE
Add "IsActive" to connection type

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/ConnectivityPlugin#8]
Copied from: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/255
## Feature Request:

ConnectionTypes returns a list of active connections, but it would be nice to know which connection is being used for network calls... I'm not sure about other platforms, but for Windows you can get the connection that's being used by calling NetworkInformation.GetInternetConnectionProfile();

Can you either order the ConnectionTypes so that the first item is the connection being used or maybe add a new property... I guess this request could get tricky if Android and iOS don't support finding the connection being used.

**Comment by adamhill** [comment]
There is the[ Reacability NuGet ](https://github.com/has-taiar/Reachability.Net) for reference.

**Comment by SaqibS** [comment]
+1 on this - the purpose of the ConnectionTypes property is slightly ambiguous - is it a list of all connections on the device? Or all active connections?

We want to know whether the network request will be sent over, say, 4G, wifi, or something else. Is it reliable to use the first item in the list?

**Comment by MichelMatthey** [comment]
I found that sometimes IsConnected is not sufficient because I want to be able to tell when the Wifi is turned on but not connected when no Wifi is in range. Without a "IsConnectedToWifi" method I can't tell if the device is connecting using the cellular network or the Wifi as both are turned on but only the cellular is connected. To make things even worse, the IsReachable returns true if the Wifi is turned on but not connected as it automatically uses the cellular network instead... So unless the Wifi is manually turned off we can't tell if it is connected ?

**Comment by MichelMatthey** [comment]
When can we have a IsConnectedToWifi and IsConnectedToCellular methods please ? Or IsConnected(connectionType)  ?

Forgot to mention, what I am trying to implement is "IsWifiAvailableAndConnected" so I can restrict the use of the network, only when Wifi is connected, the user chooses this option and we need to accurately detect if "Wifi is turned On" (And also connected of course, otherwise Wifi is considered not available) ?

**Comment by MichelMatthey** [comment]
Or a IsReachable/IsRemoteReachable method that has a useConnectionType parameter too so we know exactly if a site is reachable through Wifi or Cellular ?

We would like to avoid having to call these 2 methods if we can help it, hence IsConnected(connectionType) is what we are after ? Or we can easily call the connectionType.IsActive when it is available, but is that the same meaning ? Or could have connectionType.IsActive and also a connectionType.IsConnected method added ?

Thanks!!!
